utils:
  colors:
    - "red"
    - "gold"
    - "yellow"
    - "green"
    - "blue"
    - "purple"
  codes:
    - "italic"
    - "underline"
    - "strikethrough"
    # - "magic"

  header-template: "\n<%s><%s>%s\n"
  # 1: Colour, 2: format code, 3: Lyric
commands:

  karma:
    usage: "<red>Usage: /karma [...]"
    permission: "manager"
    permission-message: "<red>You do not have permission to run this."

    contents:
      messages:
        executed: "<gold>Started to run Karma... RIP to every player"
        completed: ""

      lyrics:
        - "I was a bad girl, I did some bad things"
        - "I swear I did it all for fun and it meant nothing"
        - "It never happened, it was a secret"
        - "Like when a tree falls in the forest, no one hears it"
        - "Another late night, another crazy mood"
        - "And I didn't think twice what it would do to you"
        - "I was a wild child, you always knew it"
        - "It was a matter of time before I blew it"
        - "Thou shall not lie, thou shall not cheat"
        - "Thou shall not get caught or you'll end up just like me, oh"
        - "Karma's a bitch, I should've known better"
        - "If I had a wish, I would've never effed around"
        - "When I saw the pics of you and her, I felt the knife twist"
        - "Karma's a bitch"
        - "And she's with you right now"
        - "She is a good girl, I think she's boring (boring)"
        - "Believe me, twenty minutes later, you'll be snoring"
        - "But it still kills me that you hooked up with her (up with her)"
        - "And now the universe is giving me what I deserve (I deserve)"
        - "Thou shall not lie, thou shall not cheat (oh, whoa)"
        - "I'll write it down a thousand times and hope it sets me free, oh"
        - "Karma's a bitch, I should've known better"
        - "If I had a wish, I would've never effed around"
        - "When I saw the pics of you and her, I felt the knife twist (karma)"
        - "Karma's a bitch (oh, whoa)"
        - "And she's with you right now"
        - "karma's a bitch"
        - "(Whoa, oh, oh, oh-oh) karma's a bitch"
        - "Better be good 'cause what goes around, comes around"
        - "Karma's a bitch"
        - "And she's with you right now"
        - "And when I lay me down to sleep, it's not your body next to me"
        - "This lonely room feels so empty, just me and my regrets"
        - "And cold blue eyes look back at me, the mirror has no sympathy"
        - "My guilt's become a symphony that won't let me forget, oh"
        - "Karma's a bitch, I should've known better"
        - "If I had a wish, I would've never effed around (oh, whoa)"
        - "When I saw the pics of you and her, I felt the knife twist (karma)"
        - "Karma's a bitch (karma)"
        - "And she's with you right now"
        - "Karma's a bitch"
        - "Karma's a bitch"
        - "Better be good 'cause what goes around, comes around"
        - "Karma's a bitch (karma)"
        - "And she's with you right now"
